image: node:10-alpine

before_script:
  - npm install

stages:
  - test
  - lint
  - build

lint:
  stage: lint
  script:
    - node_modules/.bin/nx lint
    - node_modules/.bin/ng lint

tests:
  stage: test
  script:
    - node_modules/.bin/ng test --passWithNoTests

Build production image:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ['']
  stage: build
  before_script: []
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"gitlab-ci-token\",\"password\":\"$CI_JOB_TOKEN\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile.prod --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG --destination $CI_REGISTRY_IMAGE:$latest
  only:
    - tags
    - master

Build development image:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ['']
  stage: build
  before_script: []
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"gitlab-ci-token\",\"password\":\"$CI_JOB_TOKEN\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile.dev --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA --destination $CI_REGISTRY_IMAGE:development
  only:
    - development
