FROM node:12-alpine as build
WORKDIR /app
COPY ./package.json /app/
RUN npm install
COPY . /app

RUN npm run build


FROM nginx:1.18-alpine as publish

RUN apk add --no-cache jq moreutils

COPY --from=build /app/dist/apps/open-forest-data-agregator/browser /usr/share/nginx/html
COPY docker/entrypoint.sh /

COPY docker/default.conf /etc/nginx/conf.d/default.conf

RUN chmod +x entrypoint.sh

CMD sh -c "/entrypoint.sh && \
    nginx -g 'daemon off;'"
